### ISSUE TITLE
Drawing textures ignores canvas drawing state

### ISSUE THREAD

**Issue by Tornadoally** [Redninja106/simulationframework#38]
If the canvas drawing state is to fill with a certain color, I think it'd be an improvement to use this color as the filter for the image. If you'd like the full normal color, you could do canvas.Fill(Color.White)

**Comment by Redninja106** [comment]
It might be better to simple add a `tint` parameter to `DrawTexture()` and the textured `Fill()` overloads, but this is certain a feature i will add.

**Comment by Tornadoally** [comment]
Yes that sounds much better!

**Comment by Redninja106** [comment]
added the `tint` parameter to DrawTexture() in 0.3.0 alpha
