### ISSUE TITLE
Setting Window Properties is Inconsistent

### ISSUE THREAD

**Issue by Tornadoally** [Redninja106/simulationframework#48]
It's not as pretty when setting the name is a property but the icon is a method.
Might be nicer as Window.SetName and Window.SetIcon
Or by making the icon an ITexture as a property.

**Comment by Redninja106** [comment]
I always try to expose properties over Get/Set methods when it makes sense. Unfortunately, the window icon can be set using either a texture or array, so it can't be a property.
