### ISSUE TITLE
Creating colors

### ISSUE THREAD

**Issue by Tornadoally** [Redninja106/simulationframework#50]
Unable to create a color using hex code
new Color("FFFFFF");

**Comment by Tornadoally** [comment]
Same thing goes for color creation using hsv

**Comment by Redninja106** [comment]
you actually can do this using Color.Parse:
```cs
Color color = Color.Parse("FF0000FF");
```
you can also prefix the string with # or 0x and provide 6 or 8 hex digits (with 6, alpha is assumed to be 255)

**Comment by Redninja106** [comment]
and as for HSV, can you open another issue about that?
