### ISSUE TITLE
bug: window crashes after resizing

### ISSUE THREAD

**Issue by viylouu** [Redninja106/simulationframework#60]
if you keep resizing the window too much it crashes

**Comment by viylouu** [comment]
it might just be if you use the window width and height but i use those alot so yeah

**Comment by Redninja106** [comment]
Hey, thanks for opening this issue. I cant seem to reproduce this, can you add some more details and maybe a code example that causes the crash?

**Comment by viylouu** [comment]
in my game im using the window width and height variables alot and it crashes when i resize too many times at the corner of the window
only the corner

**Comment by viylouu** [comment]
it gives an attempted to read or write protected memory error
