### ISSUE TITLE
System.AccessViolationException when resizing window

### ISSUE THREAD

**Issue by annasajkh** [Redninja106/simulationframework#65]
i got System.AccessViolationException when i resize window with a bunch of bouncing rectangles

i tried to test the framework performance with a bunch of rectangles
and when i try to resize the window i got the System.AccessViolationException
here is a video i took when the crash happend

https://github.com/Redninja106/simulationframework/assets/61279556/f0350041-fccf-46f4-837a-8402805c8258

oh this happend on the SKCanvas.cs from the SkiaSharp itself it's probably skia canvas bug then
![image](https://github.com/Redninja106/simulationframework/assets/61279556/690adcf8-c9ad-493d-9acc-9454e2640aac)
![image](https://github.com/Redninja106/simulationframework/assets/61279556/de24a419-01fb-42a2-a558-b5f394cdec63)

**Comment by annasajkh** [comment]
oh this is probably is duplicate of #60

**Comment by annasajkh** [comment]
ohhh it doesn't even need a resize to trigger the crash you just need to wait long enough
here is the repo if you want to reproduce it https://github.com/annasajkh/TestSimulationFramework

**Comment by Redninja106** [comment]
wow, this is super thorough, thanks for opening this

I've known about this bug for a while (since #60) but I could not repro it (I literally left my own apps open for hours to no avail)

I was able to get repro with your repo though. I'll figure out the cause and push a fix.

**Comment by Redninja106** [comment]
It had to do with loading custom fonts. Skia requires the font data to live as long as the font itself. So it would work fine, until the byte array containing file data was GC'ed. This is why resizing the window or drawing a lot of shapes seemed to cause the issue, as those things allocate memory and would trigger a GC. 

I'm gonna upload the next beta with the fix later today.
