### ISSUE TITLE
Return Types Missing in "Getting Started" Sample Code

### ISSUE THREAD

**Issue by stevensrmiller** [Redninja106/simulationframework#66]
Nice project.

I was able to run the sample code in the "Getting Started" section of the ReadMe. but it has a slight bug. The two methods I need to override, `OnInitialize` and `OnRender`, need to be declared with `void` return types. The example as actually written won't compile.

Cheers,
Stevens

**Comment by Redninja106** [comment]
Hey, thanks for reporting this. Not sure how I missed that lol. Will fix it now.
